name: 🐛 Bug Report
description: Something is not working as expected
title: "[Bug]: "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: dropdown
    id: bug-type
    attributes:
      label: Bug Type
      description: What kind of issue is this?
      options:
        - Tool gives incorrect output
        - Error/crash
        - UI bug
        - Performance issue
        - Other
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Expected output, actual output, steps to recreate
      description: |
        Please provide:
        - What you expected to happen
        - What actually happened
        - Steps to recreate the issue
      placeholder: |
        Expected: The subnet calculator should show...
        Actual: It shows/does...
        Steps: 1. Go to... 2. Enter... 3. Click...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Info
      description: Logs, screenshots, browser info, input data, etc.
      placeholder: |
        Browser: Chrome 120
        Input: 192.168.1.0/24
        Screenshots/logs: (paste here)

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to make sure this bug hasn't been reported before
          required: true
        - label: I agree to follow the [Code of Conduct](https://github.com/Lissy93/networking-toolbox/?tab=coc-ov-file#contributor-covenant-code-of-conduct)
          required: true